upgradepkg: indent the main loop, convert it to for-loop
By converting the main processing loop from a while loop to a for
loop, the code no longer needs to call shift.  This is slightly
better since there's no risk of forgetting to do it.

Also indent the body of the loop so that the structure is more
apparent.

diff --git a/upgradepkg b/upgradepkg
--- a/upgradepkg
+++ b/upgradepkg
@@ -159,142 +159,136 @@ package_name() {
 ERRCODE=0
 
 # Main processing loop:
-while [ ! "$1" = "" ]; do
+for ARG; do
 
-# Simple package integrity check:
-if [ ! -f $(echo $1 | cut -f 2 -d '%') ]; then
-  ERRCODE=4
-  echo "Cannot install $1:  file not found"
-  shift 1
-  continue;
-fi
-
-# Figure out the names of the old and new packages:
-OLD=$(echo $1 | cut -f 1 -d '%')
-NEW=$(echo $1 | cut -f 2 -d '%')
-INCOMINGDIR=$(dirname $NEW)
-# These are the package names with the extension:
-NNAME=$(basename $NEW)
-ONAME=$(basename $OLD)
-# These are the package names without the extension:
-OLD=$(pkgbase $OLD)
-NEW=$(pkgbase $NEW)
-
-# Make sure the extension is valid:
-if [ "$NNAME" = "$NEW" ]; then
-  # We won't throw an ERRCODE for this, but the package is skipped:
-  echo "Cannot install $1:  invalid package extension"
-  shift 1
-  continue;
-fi
-
-# Check and fix the old package name:
-SHORT="$(package_name $OLD)"
-if [ ! -r $ROOT/var/log/packages/$OLD ]; then
-  if ls $ROOT/var/log/packages/$SHORT* 1> /dev/null 2> /dev/null ; then
-    for installed_package in $ROOT/var/log/packages/$SHORT* ; do
-      if [ "$(package_name $installed_package)" = "$SHORT" ]; then # found one
-        OLD="$(basename $installed_package)"
-        break
-      fi
-    done
+  # Simple package integrity check:
+  if [ ! -f $(echo "$ARG" | cut -f 2 -d '%') ]; then
+    ERRCODE=4
+    echo "Cannot install $ARG:  file not found"
+    continue;
   fi
-fi
 
-# Test to see if both the old and new packages are where we expect them
-# to be -- skip to the next package (or package pair) if anything's wrong:
+  # Figure out the names of the old and new packages:
+  OLD=$(echo "$ARG" | cut -f 1 -d '%')
+  NEW=$(echo "$ARG" | cut -f 2 -d '%')
+  INCOMINGDIR=$(dirname $NEW)
+  # These are the package names with the extension:
+  NNAME=$(basename $NEW)
+  ONAME=$(basename $OLD)
+  # These are the package names without the extension:
+  OLD=$(pkgbase $OLD)
+  NEW=$(pkgbase $NEW)
 
-if [ ! -r $ROOT/var/log/packages/$OLD ]; then
-  if [ ! "$INSTALL_NEW" = "yes" ]; then
-    if [ "$DRY_RUN" = "true" ]; then
-      echo "$OLD would not be upgraded (no installed package named $SHORT)."
-    else  
-      echo
-      echo "Error:  there is no installed package named $OLD."
-      echo "        (looking for $ROOT/var/log/packages/$OLD)"
-      echo
+  # Make sure the extension is valid:
+  if [ "$NNAME" = "$NEW" ]; then
+    # We won't throw an ERRCODE for this, but the package is skipped:
+    echo "Cannot install $OLD:  invalid package extension"
+    continue;
+  fi
+
+  # Check and fix the old package name:
+  SHORT="$(package_name $OLD)"
+  if [ ! -r $ROOT/var/log/packages/$OLD ]; then
+    if ls $ROOT/var/log/packages/$SHORT* 1> /dev/null 2> /dev/null ; then
+      for installed_package in $ROOT/var/log/packages/$SHORT* ; do
+        if [ "$(package_name $installed_package)" = "$SHORT" ]; then # found one
+          OLD="$(basename $installed_package)"
+          break
+        fi
+      done
     fi
-    ERRCODE=1
-  else # --install-new was given, so install the new package:
-    if [ "$DRY_RUN" = "true" ]; then
-      echo "$NEW would be installed (new package)."
-    else
-      cat << EOF
+  fi
+
+  # Test to see if both the old and new packages are where we expect them
+  # to be -- skip to the next package (or package pair) if anything's wrong:
+
+  if [ ! -r $ROOT/var/log/packages/$OLD ]; then
+    if [ ! "$INSTALL_NEW" = "yes" ]; then
+      if [ "$DRY_RUN" = "true" ]; then
+        echo "$OLD would not be upgraded (no installed package named $SHORT)."
+      else
+        echo
+        echo "Error:  there is no installed package named $OLD."
+        echo "        (looking for $ROOT/var/log/packages/$OLD)"
+        echo
+      fi
+      ERRCODE=1
+    else # --install-new was given, so install the new package:
+      if [ "$DRY_RUN" = "true" ]; then
+        echo "$NEW would be installed (new package)."
+      else
+        cat << EOF
 
 +==============================================================================
 | Installing new package $INCOMINGDIR/$NNAME
 +==============================================================================
 
 EOF
-      /sbin/installpkg $INCOMINGDIR/$NNAME
+        /sbin/installpkg $INCOMINGDIR/$NNAME
+      fi
     fi
-  fi
-  shift 1
-  continue;
-elif [ ! -r "$INCOMINGDIR/$NNAME" ]; then
-  if [ "$DRY_RUN" = "true" ]; then
-    echo "$NEW incoming package not found (command line)."
-  else
-    echo
-    echo "Error:  incoming package $INCOMINGDIR/$NNAME not found."
-    echo
-  fi
-  shift 1
-  ERRCODE=1
-  continue;
-fi
-
-# Unless --reinstall was given, compare the package names
-# and skip any exact matches:
-if [ ! "$REINSTALL" = "true" ]; then
-  if [ "$OLD" = "$NEW" ]; then
+    continue;
+  elif [ ! -r "$INCOMINGDIR/$NNAME" ]; then
     if [ "$DRY_RUN" = "true" ]; then
-      echo "$NEW would be skipped (already installed)."
+      echo "$NEW incoming package not found (command line)."
     else
-      cat << EOF
+      echo
+      echo "Error:  incoming package $INCOMINGDIR/$NNAME not found."
+      echo
+    fi
+    ERRCODE=1
+    continue;
+  fi
+
+  # Unless --reinstall was given, compare the package names
+  # and skip any exact matches:
+  if [ ! "$REINSTALL" = "true" ]; then
+    if [ "$OLD" = "$NEW" ]; then
+      if [ "$DRY_RUN" = "true" ]; then
+        echo "$NEW would be skipped (already installed)."
+      else
+        cat << EOF
 
 +==============================================================================
 | Skipping package $NEW (already installed)
 +==============================================================================
 
 EOF
+      fi
+      continue;
     fi
-    shift 1
-    continue; 
   fi
-fi
 
-# Showtime.  Let's do the upgrade.  First, we will rename all the
-# installed packages with this basename to make them easy to remove later:
+  # Showtime.  Let's do the upgrade.  First, we will rename all the
+  # installed packages with this basename to make them easy to remove later:
 
-TIMESTAMP=$(date +%Y-%m-%d,%T)
-SHORT="$(package_name $OLD)"
-if [ "$DRY_RUN" = "true" ]; then
-  echo -n "$NEW would upgrade: "
+  TIMESTAMP=$(date +%Y-%m-%d,%T)
+  SHORT="$(package_name $OLD)"
+  if [ "$DRY_RUN" = "true" ]; then
+    echo -n "$NEW would upgrade: "
+    for installed_package in $ROOT/var/log/packages/$SHORT* ; do
+    if [ "$(package_name $installed_package)" = "$SHORT" ]; then
+      echo -n "$(pkgbase $installed_package)"
+    fi
+    done
+    echo
+    continue
+  fi
   for installed_package in $ROOT/var/log/packages/$SHORT* ; do
-  if [ "$(package_name $installed_package)" = "$SHORT" ]; then
-    echo -n "$(pkgbase $installed_package)"
-  fi
-  done
-  echo
-  shift 1
-  continue
-fi
-for installed_package in $ROOT/var/log/packages/$SHORT* ; do
-  if [ "$(package_name $installed_package)" = "$SHORT" ]; then
-    mv $installed_package ${installed_package}-upgraded-$TIMESTAMP
-  fi
-done
-for installed_script in $ROOT/var/log/scripts/$SHORT* ; do
-  if [ "$(package_name $installed_script)" = "$SHORT" ]; then
-    if [ -r $installed_script ]; then
-      mv $installed_script ${installed_script}-upgraded-$TIMESTAMP
+    if [ "$(package_name $installed_package)" = "$SHORT" ]; then
+      mv $installed_package ${installed_package}-upgraded-$TIMESTAMP
     fi
-  fi
-done
+  done
+  for installed_script in $ROOT/var/log/scripts/$SHORT* ; do
+    if [ "$(package_name $installed_script)" = "$SHORT" ]; then
+      if [ -r $installed_script ]; then
+        mv $installed_script ${installed_script}-upgraded-$TIMESTAMP
+      fi
+    fi
+  done
 
-# Print a banner for the current upgrade:
-cat << EOF
+  # Print a banner for the current upgrade:
+  cat << EOF
 
 +==============================================================================
 | Upgrading $OLD package using $INCOMINGDIR/$NNAME
@@ -302,64 +296,59 @@ cat << EOF
 
 EOF
 
-# Next, the new package is pre-installed:
-if [ "$VERBOSE" = "verbose" ]; then
-  /sbin/installpkg $INCOMINGDIR/$NNAME
-  RETCODE=$?
-else
-  echo "Pre-installing package $NEW..."
-  /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
-  RETCODE=$?
-fi
-# Make sure that worked:
-if [ ! $RETCODE = 0 ]; then
-  echo "ERROR:  Package $INCOMINGDIR/$NNAME did not install"
-  echo "correctly.  You may need to reinstall your old package"
-  echo "to avoid problems.  Make sure the new package is not"
-  echo "corrupted."
-  sleep 30
-  # Skip this package, but still try to proceed.  Good luck...
-  shift 1
-  continue;
-fi
+  # Next, the new package is pre-installed:
+  if [ "$VERBOSE" = "verbose" ]; then
+    /sbin/installpkg $INCOMINGDIR/$NNAME
+    RETCODE=$?
+  else
+    echo "Pre-installing package $NEW..."
+    /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
+    RETCODE=$?
+  fi
+  # Make sure that worked:
+  if [ ! $RETCODE = 0 ]; then
+    echo "ERROR:  Package $INCOMINGDIR/$NNAME did not install"
+    echo "correctly.  You may need to reinstall your old package"
+    echo "to avoid problems.  Make sure the new package is not"
+    echo "corrupted."
+    sleep 30
+    # Skip this package, but still try to proceed.  Good luck...
+    continue;
+  fi
 
-# Now, the leftovers from the old package(s) can go.  Pretty simple, huh? :)
-if [ -d "$ROOT" ]; then
-  ( cd $ROOT/var/log/packages
-    for rempkg in *-$TIMESTAMP ; do
-      if [ "$VERBOSE" = "verbose" ]; then
-        ROOT=$ROOT /sbin/removepkg $rempkg
-      else
-        ROOT=$ROOT /sbin/removepkg $rempkg | grep -v "Skipping\." | grep -v "Removing files:"
-      fi
-    done
-  )
-else
-  ( cd /var/log/packages
-    for rempkg in *-$TIMESTAMP ; do
-      if [ "$VERBOSE" = "verbose" ]; then
-        /sbin/removepkg $rempkg
-      else
-        /sbin/removepkg $rempkg | grep -v "Skipping\." | grep -v "Removing files:"
-      fi
-    done
-  )
-fi
-echo
+  # Now, the leftovers from the old package(s) can go.  Pretty simple, huh? :)
+  if [ -d "$ROOT" ]; then
+    ( cd $ROOT/var/log/packages
+      for rempkg in *-$TIMESTAMP ; do
+        if [ "$VERBOSE" = "verbose" ]; then
+          ROOT=$ROOT /sbin/removepkg $rempkg
+        else
+          ROOT=$ROOT /sbin/removepkg $rempkg | grep -v "Skipping\." | grep -v "Removing files:"
+        fi
+      done
+    )
+  else
+    ( cd /var/log/packages
+      for rempkg in *-$TIMESTAMP ; do
+        if [ "$VERBOSE" = "verbose" ]; then
+          /sbin/removepkg $rempkg
+        else
+          /sbin/removepkg $rempkg | grep -v "Skipping\." | grep -v "Removing files:"
+        fi
+      done
+    )
+  fi
+  echo
 
-# Again!  Again!
-# Seriously, the reinstalling of a package can be crucial if any files
-# shift location, so we should always reinstall as the final step:
-if [ ! "$NOT_PARANOID" = "true" ]; then
-  /sbin/installpkg $INCOMINGDIR/$NNAME
-fi
+  # Again!  Again!
+  # Seriously, the reinstalling of a package can be crucial if any files
+  # shift location, so we should always reinstall as the final step:
+  if [ ! "$NOT_PARANOID" = "true" ]; then
+    /sbin/installpkg $INCOMINGDIR/$NNAME
+  fi
 
-echo "Package $OLD upgraded with new package $INCOMINGDIR/$NNAME."
-ERRCODE=0
-
-# Process next parameter:
-shift 1
-
+  echo "Package $OLD upgraded with new package $INCOMINGDIR/$NNAME."
+  ERRCODE=0
 done
 
 if [ ! "$DRY_RUN" = "true" ]; then
